### PR TITLE
Backend Setup and Auth APIs

### LINKED ISSUE #7: Implement Signup Endpoint (`POST /auth/signup`)
We need a backend endpoint to create a new user account so the frontend can support onboarding. This is part of the MVP auction flow.

API contract reference: `docs/api/CONTRACT.md` → **Sign Up** section.

## Goal
Implement `POST /auth/signup` in the Go backend to:
- validate input
- hash password securely
- create the user record in Postgres
- return a safe user object (no password fields)

### Endpoint
- **Method:** `POST`
- **Path:** `/auth/signup`
- **Auth:** none

### Request Body
```json
{
  "email": "user@example.com",
  "password": "plain-text-password"
}
```

### Success Response
- **Status:** `201 Created`
```json
{
  "user": {
    "id": "uuid",
    "email": "user@example.com",
    "verified": false
  }
}
```

### Error Responses
- `400 VALIDATION_ERROR`
  - invalid email format
  - password too short (define minimum, e.g. 8 chars)
- `409 CONFLICT`
  - email already exists
- `500 INTERNAL_ERROR`
  - unexpected DB error

Use the standard error shape:
```json
{
  "error": {
    "code": "STRING_CODE",
    "message": "Human readable message",
    "details": {}
  }
}
```

## Implementation Notes
- Use a strong password hashing algorithm:
  - recommended: `bcrypt` (Go standard usage)
- Store only `password_hash` in DB (never store plaintext).
- Normalize email (e.g., trim spaces, lowercase) before storing.
- Ensure DB has a **unique constraint** on `users.email`.
- Return only public fields (`id`, `email`, `verified`).

### LINKED ISSUE #8: Implement Login Endpoint (`POST /auth/login`)
We need a backend endpoint to authenticate users so protected actions (posting items, bidding, uploads) can be gated behind a token.

API contract reference: `docs/api/CONTRACT.md` → **Login** section.

## Goal
Implement `POST /auth/login` in the Go backend to:
- validate input
- verify credentials (email + password)
- issue an auth token (JWT or similar)
- return the token + public user object

### Endpoint
- **Method:** `POST`
- **Path:** `/auth/login`
- **Auth:** none

### Request Body
```json
{
  "email": "user@example.com",
  "password": "plain-text-password"
}
```

### Success Response
- **Status:** `200 OK`
```json
{
  "token": "jwt-token-string",
  "user": {
    "id": "uuid",
    "email": "user@example.com",
    "verified": false
  }
}
```

### Error Responses
- `400 VALIDATION_ERROR`
  - invalid email format
  - missing/empty password
- `401 UNAUTHORIZED`
  - wrong credentials (email not found OR password mismatch)
- `500 INTERNAL_ERROR`
  - unexpected DB error

Use the standard error shape:
```json
{
  "error": {
    "code": "STRING_CODE",
    "message": "Human readable message",
    "details": {}
  }
}
```

## Token Requirements
- Use **JWT** (recommended) signed with a secret (`JWT_SECRET`).
- Token payload (minimum):
  - `sub` = user id
  - `email` (optional)
  - `iat`, `exp` (expiry required)
- Token expiry: pick something simple for MVP (e.g., 24h).

## Implementation Notes
- Normalize email (trim + lowercase) before lookup.
- Fetch user by email; compare password using `bcrypt.CompareHashAndPassword`.
- Do not reveal whether email exists: for wrong credentials always return `401 UNAUTHORIZED`.
- Return only public user fields (`id`, `email`, `verified`).

### LINKED ISSUE #24: Implement Email Verification (`POST /auth/verify`)
We support account verification via an email verification token. This endpoint should mark the user as verified when a valid token is provided.

Reference:
- `docs/api/CONTRACT.md` (Auth section)
- DB: `email_verification_tokens` table (token hash, expiry, used_at)

## Goal
Implement `POST /auth/verify` in the Go backend:
- Accept a verification token from the client
- Validate and consume the token (one-time use, not expired)
- Mark the corresponding user as `verified = true`
- Return a safe user object (no password fields)

## Endpoint
- **Method:** `POST`
- **Path:** `/auth/verify`
- **Auth:** none
- **Content-Type:** `application/json`

### Request Body
```json
{ "token": "..." }
```

### Success Response
- **Status:** `200 OK`
```json
{
  "user": {
    "id": "uuid",
    "email": "user@example.com",
    "verified": true
  }
}
```

## Expected Behaviors
- Token must be valid, not expired, and not used.
- Token must be **single-use** (cannot verify twice with the same token).
- Use DB time (`now()`) for expiry checks.

## Error Handling
Use standard error shape:
```json
{ "error": { "code": "STRING_CODE", "message": "...", "details": {} } }
```

Return:
- `400 VALIDATION_ERROR` — missing/empty token
- `401 UNAUTHORIZED` — invalid/expired/used token
- `404 NOT_FOUND` — token valid but user record missing (rare, but handle)
- `500 INTERNAL_ERROR` — unexpected errors

### LINKED ISSUE #25: Implement Backend Resend Verification Token (`POST /auth/resend-verification`)
Users may not receive the verification email/token or may need a new token if the previous one expired. This endpoint generates a new verification token and sends it (or logs it in dev).

Reference:
- `docs/api/CONTRACT.md` (Auth section)
- DB: `email_verification_tokens` table

## Goal
Implement `POST /auth/resend-verification` in the Go backend:
- Accept an email address
- If user exists and is unverified, create a new verification token
- Deliver token via email provider OR log token/link in dev mode
- Return a generic success response (avoid leaking whether the email exists)

## Endpoint
- **Method:** `POST`
- **Path:** `/auth/resend-verification`
- **Auth:** none
- **Content-Type:** `application/json`

### Request Body
```json
{ "email": "user@example.com" }
```

### Success Response
- **Status:** `200 OK`
```json
{ "ok": true }
```
(Or an empty body is acceptable.)

## Expected Behaviors
- Normalize email (trim + lowercase).
- If user does not exist: still return `200` (do not leak).
- If user already verified: return `200` (no-op).
- If user is unverified:
  - create a new token (single-use, expiring)
  - store **token hash** in DB
  - send/log the token

## Error Handling
Use standard error shape:
```json
{ "error": { "code": "STRING_CODE", "message": "...", "details": {} } }
```

Return:
- `400 VALIDATION_ERROR` — invalid email format / missing email
- `500 INTERNAL_ERROR` — unexpected errors

### PR DESCRIPTION
**Pull request by AndrewJanong**
This PR provides initial setup for the Golang Backend with implementations on Auth APIs/services.

### Description:
- Implemented auth endpoints:
  - `POST /auth/signup`
  - `POST /auth/login`
  - `POST /auth/verify`
  - `POST /auth/resend-verification`
- Added email verification token generation (single-use + expiry)
- Updated login to block unverified users
- Added middleware:
  - CORS (for frontend integration)
  - JWT auth middleware (for protected routes)
- Added DB migration for `email_verification_tokens` and updated documentation

### Related Issues:
- Resolved #7 
- Resolved #8 
- Resolved #24 
- Resolved #25

### CODE REVIEW

File: apps/backend/middlewares/cors.go [hunk 1]
```diff
@@ -0,0 +1,32 @@
+package middleware
```
Comment (FerdiHS) [inline apps/backend/middlewares/cors.go]: I think we should either change the package name to `middlewares` or change the folder name to `middleware`. I would prefer the first option to maintain consistency with other modules.

**Review by FerdiHS — CHANGES_REQUESTED** [review]
Thanks @AndrewJanong for helping setting up the backend. Can you provide the instructions on how to setup and run the backend service in the `README.md` file? Also please provide an `.env.example` file inside the `apps/backend/` directory to help others to run the backend program.
